#!/usr/bin/env bash
# show information about subdomains

if [ "$#" -eq 2 ]; then
    dig $2.$1 | grep -A1 'ANSWER SECTION:' | sed -n 2p  | awk '{print "The subdomain '$2' is a " $4 " record and points to " $5}'
elif [ "$#" -eq 1 ]; then
    for subdomain in 'www' 'lb-01' 'web-01' 'web-02'; do
        dig $subdomain.$1 | grep -A1 'ANSWER SECTION:' | sed -n 2p  | awk '{print "The subdomain '$subdomain' is a " $4 " record and points to " $5}'
    done
fi
