#!/usr/bin/env bash                                                             
# script that Install nginx on the web-01 server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo chown -R ubuntu /var/www/html/
echo "Holberton School for the win!" > /var/www/html/index.html
