#!/usr/bin/env bash                                                             
# script that Install nginx on the web-01 server and configure site with code 301

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu /var/www/html/
sudo echo "Holberton School for the win!" > /var/www/html/index.html
sudo chown -R ubuntu /etc/nginx/sites-enabled/
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4t permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
