#!/usr/bin/env bash                                                             
#!/usr/bin/env bash                                                             
# script that Install nginx on the web-01 server and configure site with code 301

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu /var/www/html/
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo chown -R ubuntu /etc/nginx/sites-enabled/
server="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4t permanent;"
sudo sed -i "/server_name _;/$server/" /etc/nginx/sites-enabled/default
sudo service nginx start                             
newstring="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$server$newstring/" /etc/nginx/sites-enabled/defaultc/nginx/sites-available/default
