#!/usr/bin/env bash                                                             
# script that Install HAProxy and configure it for 2 servers

sudo apt-get update
sudo apt-get install -y haproxy
sudo chown -R "$USER" /etc/haproxy/

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxyo.cfg
sudo echo "
frontend webserver
        bind *: 80
        default_backend appserver

backend appserver
        balance roundrobin
        server 2843-web-01 35.190.183.78:80 check
        server 2843-web-02 34.226.194.149:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
