#!/usr/bin/env bash
#This script is displaying "Holberton School" 10 times but in the
#nine interaction print Hi

count=1
while [ $count -le 10 ]
do
	echo "Holberton School"
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	((count++))
done
